### ISSUE TITLE
ModuleNotFoundError: No module named 'future' 

### ISSUE THREAD

**Issue by elvischao** [elpaso/qgis-geocoding#26]
无法载入插件“GeoCoding”因在调用其classFactory()方法时发生错误 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/__init__.py", line 24, in classFactory
    from .GeoCoding import GeoCoding
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/GeoCoding.py", line 47, in 
    from .geocoders import *
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/geocoders.py", line 20, in 
    from .networkaccessmanager import NetworkAccessManager
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoCoding/networkaccessmanager.py", line 21, in 
    from future import standard_library
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python版本： 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS版本： 3.0.2-Girona Girona, exported 

Python路径：
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/Elvis/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by ravi9884** [comment]
Have the same issue

**Comment by ravi9884** [comment]
I can resolve this issue by installing future outside qgis

```
/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3 install future
```

**Comment by MtnBiker** [comment]
@ravi9884 Thanks. Worked for me on macOS 10.14.2.
