### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'data'


### ISSUE THREAD

**Issue by Leshy2020** [elpaso/qgis-geocoding#33]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\nextgis_connect\tree_panel.py", line 828, in import_qgis_project
    self.iface,
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\nextgis_connect\ngw_api\qt\qt_ngw_resource_base_model.py", line 131, in wrapper
    job = method(self, *args, **kwargs)
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\nextgis_connect\ngw_api\qgis\ngw_resource_model_4qgis.py", line 105, in tryImportCurentQGISProject
    index = self._nearest_ngw_group_resource_parent(index)
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\nextgis_connect\ngw_api\qt\qt_ngw_resource_base_model.py", line 273, in _nearest_ngw_group_resource_parent
    ngw_resource = item.data(0, QNGWResourceItem.NGWResourceRole)
AttributeError: 'NoneType' object has no attribute 'data'

```
GeoCoding 2.14, QGIS 2.18.28-Las Palmas on Windows 10

**Comment by eugenethepooh** [comment]
Have you been able to solve the problem? I have the same one
